### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'todense'

### ISSUE THREAD

**Issue by rgranit** [bendemeo/scalpel#1]
When running the reducer I encounter this issue:

`AttributeError: 'numpy.ndarray' object has no attribute 'todense'`

Any specific version of numpy is required? using `v1.19.2`

Thanks

**Comment by bendemeo** [comment]
Hi @rgranit, and thanks for pointing this out! The current iteration of Scalpel expects sparse matrices as transcript counts, so you must coerce the input to a sparse matrix before applying Scalpel. You can do this using the csr_matrix function from scipy.sparse:

```
from scipy.sparse import csr_matrix
adata.X = csr_matrix(adata.X)
```
The next commit will fix this issue.

**Comment by rgranit** [comment]
Thanks @bendemeo, this did solve the issue.
